#!/bin/sh
set -eu

environment_name="SUB2API_CONSOLE_FRONTEND_TRUSTED_PROXY_CIDRS"
api_upstream_name="SUB2API_CONSOLE_API_UPSTREAM"
config_file="/etc/nginx/conf.d/00-sub2api-trusted-proxies.conf"
raw_cidrs="${SUB2API_CONSOLE_FRONTEND_TRUSTED_PROXY_CIDRS:-}"
api_upstream="${SUB2API_CONSOLE_API_UPSTREAM:-api:8080}"
api_upstream_resolve=false
temporary_directory="$(mktemp -d)"
real_ip_directives="${temporary_directory}/real-ip.conf"
geo_entries="${temporary_directory}/geo.conf"
generated_config="${temporary_directory}/trusted-proxies.conf"

cleanup() {
  rm -rf "$temporary_directory"
}
trap cleanup EXIT
trap 'exit 129' HUP
trap 'exit 130' INT
trap 'exit 143' TERM

invalid_cidrs() {
  echo "$environment_name must be a comma-separated list of valid IPv4 or IPv6 CIDRs" >&2
  exit 1
}

invalid_api_upstream() {
  echo "$api_upstream_name must be unix:/absolute/path.sock or a hostname/IPv4 address followed by a port from 1 to 65535" >&2
  exit 1
}

is_ipv4_literal() {
  printf '%s\n' "$1" | awk -F. '
    NF != 4 { exit 1 }
    {
      for (octet = 1; octet <= 4; octet++) {
        if ($octet !~ /^[0-9]+$/ || $octet + 0 > 255) {
          exit 1
        }
      }
    }
  '
}

case "$api_upstream" in
  unix:*)
    api_upstream_socket="${api_upstream#unix:}"
    case "$api_upstream_socket" in
      /*) ;;
      *) invalid_api_upstream ;;
    esac
    case "$api_upstream_socket" in
      *[!0-9A-Za-z._/-]*) invalid_api_upstream ;;
    esac
    api_upstream_server="unix:$api_upstream_socket"
    ;;
  *)
    api_upstream_host="${api_upstream%:*}"
    api_upstream_port="${api_upstream##*:}"
    if [ -z "$api_upstream_host" ] || [ "$api_upstream_host" = "$api_upstream" ]; then
      invalid_api_upstream
    fi
    case "$api_upstream_host" in
      *[!0-9A-Za-z._-]*) invalid_api_upstream ;;
    esac
    case "$api_upstream_port" in
      "" | *[!0-9]*) invalid_api_upstream ;;
    esac
    if [ "${#api_upstream_port}" -gt 5 ] || [ "$api_upstream_port" -lt 1 ] || [ "$api_upstream_port" -gt 65535 ]; then
      invalid_api_upstream
    fi
    api_upstream_server="$api_upstream"
    if ! is_ipv4_literal "$api_upstream_host"; then
      api_upstream_resolve=true
    fi
    ;;
esac

: >"$real_ip_directives"
: >"$geo_entries"

remaining="$raw_cidrs"
while [ -n "$remaining" ]; do
  has_more=false
  case "$remaining" in
    *,*)
      cidr="${remaining%%,*}"
      remaining="${remaining#*,}"
      has_more=true
      ;;
    *)
      cidr="$remaining"
      remaining=""
      ;;
  esac

  cidr="$(printf '%s' "$cidr" | sed 's/^[[:space:]]*//; s/[[:space:]]*$//')"
  address="${cidr%/*}"
  prefix_length="${cidr##*/}"
  if [ -z "$cidr" ] || [ "$address" = "$cidr" ] || [ -z "$address" ] || [ -z "$prefix_length" ]; then
    invalid_cidrs
  fi
  case "$address" in
    *[!0-9A-Fa-f:.]*) invalid_cidrs ;;
  esac
  case "$prefix_length" in
    *[!0-9]*) invalid_cidrs ;;
  esac

  printf 'set_real_ip_from %s;\n' "$cidr" >>"$real_ip_directives"
  printf '  %s 1;\n' "$cidr" >>"$geo_entries"

  if [ "$has_more" = true ] && [ -z "$remaining" ]; then
    invalid_cidrs
  fi
done

{
  echo '# Generated by 40-configure-trusted-proxies.sh; do not edit.'
  echo 'upstream sub2api_console_api {'
  if [ "$api_upstream_resolve" = true ]; then
    echo '  zone sub2api_console_api 64k;'
    echo '  resolver 127.0.0.11 valid=10s ipv6=off;'
    echo '  resolver_timeout 5s;'
    printf '  server %s resolve;\n' "$api_upstream_server"
  else
    printf '  server %s;\n' "$api_upstream_server"
  fi
  echo '}'
  echo
  echo 'real_ip_header X-Forwarded-For;'
  echo 'real_ip_recursive on;'
  sed -n 'p' "$real_ip_directives"
  echo
  echo 'geo $realip_remote_addr $sub2api_console_trusted_proxy {'
  echo '  default 0;'
  sed -n 'p' "$geo_entries"
  echo '}'
  echo
  echo 'map "$sub2api_console_trusted_proxy:$http_x_forwarded_proto" $sub2api_console_forwarded_proto {'
  echo '  default $scheme;'
  echo '  "~*^1:http$" http;'
  echo '  "~*^1:https$" https;'
  echo '}'
} >"$generated_config"

mv "$generated_config" "$config_file"
nginx -t -q
