import type { WorkbenchTemplate } from "../types";

export const template: WorkbenchTemplate = {
  id: "template-one",
  name: "团队模板",
  source_id: "41",
  source_name: "来源账号",
  source_version: "source-v1",
  synced_at: "2026-09-17T10:00:00Z",
  revision: 1,
  config: {
    concurrency: 0,
    priority: 50,
    rate_multiplier: "0.1234567890123456789",
    load_factor: null,
    proxy_id: null,
    group_ids: ["7"],
    auto_pause_on_expired: true,
    expires_at: null,
    notes: "",
    credential_extras: { plan_type: "prolite", model_mapping: { "gpt-5": "gpt-5.6" } },
    extra: { codex_fingerprint_mode: "session" },
  },
  summary: {
    id: "41",
    name: "来源账号",
    email: "owner@example.test",
    status: "active",
    schedulable: true,
    plan: "prolite",
    groups: [{ id: "7", name: "团队" }],
    proxy_name: "",
    concurrency: "0",
    load_factor: "",
    rate_multiplier: "0.1234567890123456789",
    model_mapping: { "gpt-5": "gpt-5.6" },
    fingerprint: "session",
  },
};
