import type { TrafficRanking } from "@/api";

export const rankingFixture: TrafficRanking = {
  start_at: "2026-08-30T12:00:00Z",
  end_at: "2026-08-31T12:00:00Z",
  group_name: "",
  sort_by: "traffic",
  bucket: "hour",
  total_requests: 1250,
  accounts_with_traffic: 1,
  accounts: [
    {
      rank: 1,
      account_id: "41",
      account_name: "稳定主账号",
      upstream_host: "api.example",
      platform: "anthropic",
      groups: ["codex"],
      requests: 1250,
      successful: 1245,
      failed: 5,
      traffic_share: 100,
      success_rate: 99.6,
      stability_score: 99.08,
      average_latency_ms: 820,
      p95_latency_ms: 1450,
      active_buckets: 22,
      total_buckets: 24,
      latest_at: "2026-08-31T11:58:00Z",
      input_tokens: 120000,
      output_tokens: 45000,
      cache_read_tokens: 8000,
      cache_write_tokens: 1200,
      usage_available: true,
    },
    {
      rank: 2,
      account_id: "42",
      account_name: "待接入账号",
      upstream_host: "",
      platform: "openai",
      groups: ["codex"],
      requests: 0,
      successful: 0,
      failed: 0,
      traffic_share: null,
      success_rate: null,
      stability_score: null,
      average_latency_ms: null,
      p95_latency_ms: null,
      active_buckets: 0,
      total_buckets: 24,
      latest_at: null,
      input_tokens: null,
      output_tokens: null,
      cache_read_tokens: null,
      cache_write_tokens: null,
      usage_available: false,
    },
  ],
};
