export const upstreamConcurrencyLabels = {
  heading: "并发",
  name: "上游并发",
  limit: "用户上限",
  allocated: "已配置",
  allocatedName: "已配置并发",
  target: "目标",
  targetName: "目标并发",
  unknown: "未读取",
  unlimited: "不限",
  unknownAllocation: "未知 / 不限",
  stale: "缓存额度",
  exceeded: "已超上限",
  ratio: "当前并发与用户上限",
  detailTitle: "共享并发",
  detailDescription: "关联账号共用上游用户额度，显示值为配置容量。",
  unreadHint: "通过「同步上游」读取用户并发上限。",
  help: "Sub2API 用户并发上限通过「同步余额」或「同步上游」读取。已配置表示关联账号的配置容量，不代表实时请求用量；未知 / 不限表示存在配置未读取或未限制并发的账号。完全模式下开启「上游超额自动下调」可独立降低超额并发，必要时暂停低优先级账号；不受全局并发预算影响，不自动扩容或恢复账号。开启「智能扩容」后按策略分配；完全模式下同时开启「并发上限自动执行」与「调度状态自动执行」，额度恢复后自动评估并恢复符合条件的账号；分配仍受全局、单账号、步长和冷却限制。缓存额度表示本次未能确认最新上限。",
} as const;
