export const upstreamConcurrencyLabels = {
  heading: "并发",
  name: "上游并发",
  limit: "用户上限",
  allocated: "已配置",
  allocatedName: "已配置并发",
  target: "目标",
  targetName: "目标并发",
  unknown: "未读取",
  unlimited: "不限",
  unknownAllocation: "未知 / 不限",
  stale: "缓存额度",
  exceeded: "已超上限",
  ratio: "当前并发与用户上限",
  detailTitle: "共享并发",
  detailDescription: "关联账号共用上游用户额度，显示值为配置容量。",
  unreadHint: "通过「同步上游」读取用户并发上限。",
  help: "Sub2API 用户并发上限通过「同步余额」或「同步上游」读取。已配置表示关联账号的配置容量，不代表实时请求用量；未知 / 不限表示存在配置未读取或未限制并发的账号。完全模式下开启「上游共享并发分配」，系统在上游额度内先为健康账号各分配至少 1 个并发，再按权重分配剩余额度；不足时等待，容量释放确认后自动恢复。智能扩容关闭时不应用全局上限；开启时遵守已配置的扩容限制和自动执行开关。人工及范围外账号保留容量。缓存额度仅允许下调。",
} as const;
