/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app-routes/__root'
import { Route as IndexRouteImport } from './app-routes/index'
import { Route as AccountsRouteImport } from './app-routes/accounts'
import { Route as AlertPolicyRouteImport } from './app-routes/alert-policy'
import { Route as AlertsRouteImport } from './app-routes/alerts'
import { Route as AutoInspectionRouteImport } from './app-routes/auto-inspection'
import { Route as ConfigRouteImport } from './app-routes/config'
import { Route as GroupsRouteImport } from './app-routes/groups'
import { Route as LogsRouteImport } from './app-routes/logs'
import { Route as ModelCheckRouteImport } from './app-routes/model-check'
import { Route as NewapiRouteRouteImport } from './app-routes/newapi/route'
import { Route as OnboardingRouteImport } from './app-routes/onboarding'
import { Route as PolicyRouteImport } from './app-routes/policy'
import { Route as PricingRouteImport } from './app-routes/pricing'
import { Route as PricingConfigRouteImport } from './app-routes/pricing-config'
import { Route as ProfileRouteImport } from './app-routes/profile'
import { Route as RevenueAnalysisRouteImport } from './app-routes/revenue-analysis'
import { Route as SystemInfoRouteImport } from './app-routes/system-info'
import { Route as TraceRouteImport } from './app-routes/trace'
import { Route as TrafficRouteImport } from './app-routes/traffic'
import { Route as UpstreamsRouteImport } from './app-routes/upstreams'
import { Route as UptimeKumaRouteRouteImport } from './app-routes/uptime-kuma/route'
import { Route as VaultRouteImport } from './app-routes/vault'
import { Route as NewapiIndexRouteImport } from './app-routes/newapi/index'
import { Route as NewapiChannelsRouteImport } from './app-routes/newapi/channels'
import { Route as NewapiDifferencesRouteImport } from './app-routes/newapi/differences'
import { Route as NewapiGroupsRouteImport } from './app-routes/newapi/groups'
import { Route as NewapiPricesRouteImport } from './app-routes/newapi/prices'
import { Route as UptimeKumaIndexRouteImport } from './app-routes/uptime-kuma/index'
import { Route as UptimeKumaConfigRouteImport } from './app-routes/uptime-kuma/config'
import { Route as UptimeKumaStatusPagesRouteImport } from './app-routes/uptime-kuma/status-pages'
import { Route as UptimeKumaTemplatesRouteImport } from './app-routes/uptime-kuma/templates'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsRoute = AccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertPolicyRoute = AlertPolicyRouteImport.update({
  id: '/alert-policy',
  path: '/alert-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AutoInspectionRoute = AutoInspectionRouteImport.update({
  id: '/auto-inspection',
  path: '/auto-inspection',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigRoute = ConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsRoute = GroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelCheckRoute = ModelCheckRouteImport.update({
  id: '/model-check',
  path: '/model-check',
  getParentRoute: () => rootRouteImport,
} as any)
const NewapiRouteRoute = NewapiRouteRouteImport.update({
  id: '/newapi',
  path: '/newapi',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PolicyRoute = PolicyRouteImport.update({
  id: '/policy',
  path: '/policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingConfigRoute = PricingConfigRouteImport.update({
  id: '/pricing-config',
  path: '/pricing-config',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RevenueAnalysisRoute = RevenueAnalysisRouteImport.update({
  id: '/revenue-analysis',
  path: '/revenue-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemInfoRoute = SystemInfoRouteImport.update({
  id: '/system-info',
  path: '/system-info',
  getParentRoute: () => rootRouteImport,
} as any)
const TraceRoute = TraceRouteImport.update({
  id: '/trace',
  path: '/trace',
  getParentRoute: () => rootRouteImport,
} as any)
const TrafficRoute = TrafficRouteImport.update({
  id: '/traffic',
  path: '/traffic',
  getParentRoute: () => rootRouteImport,
} as any)
const UpstreamsRoute = UpstreamsRouteImport.update({
  id: '/upstreams',
  path: '/upstreams',
  getParentRoute: () => rootRouteImport,
} as any)
const UptimeKumaRouteRoute = UptimeKumaRouteRouteImport.update({
  id: '/uptime-kuma',
  path: '/uptime-kuma',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultRoute = VaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => rootRouteImport,
} as any)
const NewapiIndexRoute = NewapiIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NewapiRouteRoute,
} as any)
const NewapiChannelsRoute = NewapiChannelsRouteImport.update({
  id: '/channels',
  path: '/channels',
  getParentRoute: () => NewapiRouteRoute,
} as any)
const NewapiDifferencesRoute = NewapiDifferencesRouteImport.update({
  id: '/differences',
  path: '/differences',
  getParentRoute: () => NewapiRouteRoute,
} as any)
const NewapiGroupsRoute = NewapiGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => NewapiRouteRoute,
} as any)
const NewapiPricesRoute = NewapiPricesRouteImport.update({
  id: '/prices',
  path: '/prices',
  getParentRoute: () => NewapiRouteRoute,
} as any)
const UptimeKumaIndexRoute = UptimeKumaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UptimeKumaRouteRoute,
} as any)
const UptimeKumaConfigRoute = UptimeKumaConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => UptimeKumaRouteRoute,
} as any)
const UptimeKumaStatusPagesRoute = UptimeKumaStatusPagesRouteImport.update({
  id: '/status-pages',
  path: '/status-pages',
  getParentRoute: () => UptimeKumaRouteRoute,
} as any)
const UptimeKumaTemplatesRoute = UptimeKumaTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => UptimeKumaRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/newapi': typeof NewapiRouteRouteWithChildren
  '/uptime-kuma': typeof UptimeKumaRouteRouteWithChildren
  '/accounts': typeof AccountsRoute
  '/alert-policy': typeof AlertPolicyRoute
  '/alerts': typeof AlertsRoute
  '/auto-inspection': typeof AutoInspectionRoute
  '/config': typeof ConfigRoute
  '/groups': typeof GroupsRoute
  '/logs': typeof LogsRoute
  '/model-check': typeof ModelCheckRoute
  '/onboarding': typeof OnboardingRoute
  '/policy': typeof PolicyRoute
  '/pricing': typeof PricingRoute
  '/pricing-config': typeof PricingConfigRoute
  '/profile': typeof ProfileRoute
  '/revenue-analysis': typeof RevenueAnalysisRoute
  '/system-info': typeof SystemInfoRoute
  '/trace': typeof TraceRoute
  '/traffic': typeof TrafficRoute
  '/upstreams': typeof UpstreamsRoute
  '/vault': typeof VaultRoute
  '/newapi/channels': typeof NewapiChannelsRoute
  '/newapi/differences': typeof NewapiDifferencesRoute
  '/newapi/groups': typeof NewapiGroupsRoute
  '/newapi/prices': typeof NewapiPricesRoute
  '/uptime-kuma/config': typeof UptimeKumaConfigRoute
  '/uptime-kuma/status-pages': typeof UptimeKumaStatusPagesRoute
  '/uptime-kuma/templates': typeof UptimeKumaTemplatesRoute
  '/newapi/': typeof NewapiIndexRoute
  '/uptime-kuma/': typeof UptimeKumaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/alert-policy': typeof AlertPolicyRoute
  '/alerts': typeof AlertsRoute
  '/auto-inspection': typeof AutoInspectionRoute
  '/config': typeof ConfigRoute
  '/groups': typeof GroupsRoute
  '/logs': typeof LogsRoute
  '/model-check': typeof ModelCheckRoute
  '/onboarding': typeof OnboardingRoute
  '/policy': typeof PolicyRoute
  '/pricing': typeof PricingRoute
  '/pricing-config': typeof PricingConfigRoute
  '/profile': typeof ProfileRoute
  '/revenue-analysis': typeof RevenueAnalysisRoute
  '/system-info': typeof SystemInfoRoute
  '/trace': typeof TraceRoute
  '/traffic': typeof TrafficRoute
  '/upstreams': typeof UpstreamsRoute
  '/vault': typeof VaultRoute
  '/newapi/channels': typeof NewapiChannelsRoute
  '/newapi/differences': typeof NewapiDifferencesRoute
  '/newapi/groups': typeof NewapiGroupsRoute
  '/newapi/prices': typeof NewapiPricesRoute
  '/uptime-kuma/config': typeof UptimeKumaConfigRoute
  '/uptime-kuma/status-pages': typeof UptimeKumaStatusPagesRoute
  '/uptime-kuma/templates': typeof UptimeKumaTemplatesRoute
  '/newapi': typeof NewapiIndexRoute
  '/uptime-kuma': typeof UptimeKumaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/newapi': typeof NewapiRouteRouteWithChildren
  '/uptime-kuma': typeof UptimeKumaRouteRouteWithChildren
  '/accounts': typeof AccountsRoute
  '/alert-policy': typeof AlertPolicyRoute
  '/alerts': typeof AlertsRoute
  '/auto-inspection': typeof AutoInspectionRoute
  '/config': typeof ConfigRoute
  '/groups': typeof GroupsRoute
  '/logs': typeof LogsRoute
  '/model-check': typeof ModelCheckRoute
  '/onboarding': typeof OnboardingRoute
  '/policy': typeof PolicyRoute
  '/pricing': typeof PricingRoute
  '/pricing-config': typeof PricingConfigRoute
  '/profile': typeof ProfileRoute
  '/revenue-analysis': typeof RevenueAnalysisRoute
  '/system-info': typeof SystemInfoRoute
  '/trace': typeof TraceRoute
  '/traffic': typeof TrafficRoute
  '/upstreams': typeof UpstreamsRoute
  '/vault': typeof VaultRoute
  '/newapi/channels': typeof NewapiChannelsRoute
  '/newapi/differences': typeof NewapiDifferencesRoute
  '/newapi/groups': typeof NewapiGroupsRoute
  '/newapi/prices': typeof NewapiPricesRoute
  '/uptime-kuma/config': typeof UptimeKumaConfigRoute
  '/uptime-kuma/status-pages': typeof UptimeKumaStatusPagesRoute
  '/uptime-kuma/templates': typeof UptimeKumaTemplatesRoute
  '/newapi/': typeof NewapiIndexRoute
  '/uptime-kuma/': typeof UptimeKumaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/newapi'
    | '/uptime-kuma'
    | '/accounts'
    | '/alert-policy'
    | '/alerts'
    | '/auto-inspection'
    | '/config'
    | '/groups'
    | '/logs'
    | '/model-check'
    | '/onboarding'
    | '/policy'
    | '/pricing'
    | '/pricing-config'
    | '/profile'
    | '/revenue-analysis'
    | '/system-info'
    | '/trace'
    | '/traffic'
    | '/upstreams'
    | '/vault'
    | '/newapi/channels'
    | '/newapi/differences'
    | '/newapi/groups'
    | '/newapi/prices'
    | '/uptime-kuma/config'
    | '/uptime-kuma/status-pages'
    | '/uptime-kuma/templates'
    | '/newapi/'
    | '/uptime-kuma/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounts'
    | '/alert-policy'
    | '/alerts'
    | '/auto-inspection'
    | '/config'
    | '/groups'
    | '/logs'
    | '/model-check'
    | '/onboarding'
    | '/policy'
    | '/pricing'
    | '/pricing-config'
    | '/profile'
    | '/revenue-analysis'
    | '/system-info'
    | '/trace'
    | '/traffic'
    | '/upstreams'
    | '/vault'
    | '/newapi/channels'
    | '/newapi/differences'
    | '/newapi/groups'
    | '/newapi/prices'
    | '/uptime-kuma/config'
    | '/uptime-kuma/status-pages'
    | '/uptime-kuma/templates'
    | '/newapi'
    | '/uptime-kuma'
  id:
    | '__root__'
    | '/'
    | '/newapi'
    | '/uptime-kuma'
    | '/accounts'
    | '/alert-policy'
    | '/alerts'
    | '/auto-inspection'
    | '/config'
    | '/groups'
    | '/logs'
    | '/model-check'
    | '/onboarding'
    | '/policy'
    | '/pricing'
    | '/pricing-config'
    | '/profile'
    | '/revenue-analysis'
    | '/system-info'
    | '/trace'
    | '/traffic'
    | '/upstreams'
    | '/vault'
    | '/newapi/channels'
    | '/newapi/differences'
    | '/newapi/groups'
    | '/newapi/prices'
    | '/uptime-kuma/config'
    | '/uptime-kuma/status-pages'
    | '/uptime-kuma/templates'
    | '/newapi/'
    | '/uptime-kuma/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NewapiRouteRoute: typeof NewapiRouteRouteWithChildren
  UptimeKumaRouteRoute: typeof UptimeKumaRouteRouteWithChildren
  AccountsRoute: typeof AccountsRoute
  AlertPolicyRoute: typeof AlertPolicyRoute
  AlertsRoute: typeof AlertsRoute
  AutoInspectionRoute: typeof AutoInspectionRoute
  ConfigRoute: typeof ConfigRoute
  GroupsRoute: typeof GroupsRoute
  LogsRoute: typeof LogsRoute
  ModelCheckRoute: typeof ModelCheckRoute
  OnboardingRoute: typeof OnboardingRoute
  PolicyRoute: typeof PolicyRoute
  PricingRoute: typeof PricingRoute
  PricingConfigRoute: typeof PricingConfigRoute
  ProfileRoute: typeof ProfileRoute
  RevenueAnalysisRoute: typeof RevenueAnalysisRoute
  SystemInfoRoute: typeof SystemInfoRoute
  TraceRoute: typeof TraceRoute
  TrafficRoute: typeof TrafficRoute
  UpstreamsRoute: typeof UpstreamsRoute
  VaultRoute: typeof VaultRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts': {
      id: '/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alert-policy': {
      id: '/alert-policy'
      path: '/alert-policy'
      fullPath: '/alert-policy'
      preLoaderRoute: typeof AlertPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auto-inspection': {
      id: '/auto-inspection'
      path: '/auto-inspection'
      fullPath: '/auto-inspection'
      preLoaderRoute: typeof AutoInspectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config': {
      id: '/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof ConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups': {
      id: '/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof GroupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/model-check': {
      id: '/model-check'
      path: '/model-check'
      fullPath: '/model-check'
      preLoaderRoute: typeof ModelCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newapi': {
      id: '/newapi'
      path: '/newapi'
      fullPath: '/newapi'
      preLoaderRoute: typeof NewapiRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policy': {
      id: '/policy'
      path: '/policy'
      fullPath: '/policy'
      preLoaderRoute: typeof PolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing-config': {
      id: '/pricing-config'
      path: '/pricing-config'
      fullPath: '/pricing-config'
      preLoaderRoute: typeof PricingConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/revenue-analysis': {
      id: '/revenue-analysis'
      path: '/revenue-analysis'
      fullPath: '/revenue-analysis'
      preLoaderRoute: typeof RevenueAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system-info': {
      id: '/system-info'
      path: '/system-info'
      fullPath: '/system-info'
      preLoaderRoute: typeof SystemInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trace': {
      id: '/trace'
      path: '/trace'
      fullPath: '/trace'
      preLoaderRoute: typeof TraceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/traffic': {
      id: '/traffic'
      path: '/traffic'
      fullPath: '/traffic'
      preLoaderRoute: typeof TrafficRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upstreams': {
      id: '/upstreams'
      path: '/upstreams'
      fullPath: '/upstreams'
      preLoaderRoute: typeof UpstreamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uptime-kuma': {
      id: '/uptime-kuma'
      path: '/uptime-kuma'
      fullPath: '/uptime-kuma'
      preLoaderRoute: typeof UptimeKumaRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vault': {
      id: '/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof VaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newapi/': {
      id: '/newapi/'
      path: '/'
      fullPath: '/newapi/'
      preLoaderRoute: typeof NewapiIndexRouteImport
      parentRoute: typeof NewapiRouteRoute
    }
    '/newapi/channels': {
      id: '/newapi/channels'
      path: '/channels'
      fullPath: '/newapi/channels'
      preLoaderRoute: typeof NewapiChannelsRouteImport
      parentRoute: typeof NewapiRouteRoute
    }
    '/newapi/differences': {
      id: '/newapi/differences'
      path: '/differences'
      fullPath: '/newapi/differences'
      preLoaderRoute: typeof NewapiDifferencesRouteImport
      parentRoute: typeof NewapiRouteRoute
    }
    '/newapi/groups': {
      id: '/newapi/groups'
      path: '/groups'
      fullPath: '/newapi/groups'
      preLoaderRoute: typeof NewapiGroupsRouteImport
      parentRoute: typeof NewapiRouteRoute
    }
    '/newapi/prices': {
      id: '/newapi/prices'
      path: '/prices'
      fullPath: '/newapi/prices'
      preLoaderRoute: typeof NewapiPricesRouteImport
      parentRoute: typeof NewapiRouteRoute
    }
    '/uptime-kuma/': {
      id: '/uptime-kuma/'
      path: '/'
      fullPath: '/uptime-kuma/'
      preLoaderRoute: typeof UptimeKumaIndexRouteImport
      parentRoute: typeof UptimeKumaRouteRoute
    }
    '/uptime-kuma/config': {
      id: '/uptime-kuma/config'
      path: '/config'
      fullPath: '/uptime-kuma/config'
      preLoaderRoute: typeof UptimeKumaConfigRouteImport
      parentRoute: typeof UptimeKumaRouteRoute
    }
    '/uptime-kuma/status-pages': {
      id: '/uptime-kuma/status-pages'
      path: '/status-pages'
      fullPath: '/uptime-kuma/status-pages'
      preLoaderRoute: typeof UptimeKumaStatusPagesRouteImport
      parentRoute: typeof UptimeKumaRouteRoute
    }
    '/uptime-kuma/templates': {
      id: '/uptime-kuma/templates'
      path: '/templates'
      fullPath: '/uptime-kuma/templates'
      preLoaderRoute: typeof UptimeKumaTemplatesRouteImport
      parentRoute: typeof UptimeKumaRouteRoute
    }
  }
}

interface NewapiRouteRouteChildren {
  NewapiChannelsRoute: typeof NewapiChannelsRoute
  NewapiDifferencesRoute: typeof NewapiDifferencesRoute
  NewapiGroupsRoute: typeof NewapiGroupsRoute
  NewapiPricesRoute: typeof NewapiPricesRoute
  NewapiIndexRoute: typeof NewapiIndexRoute
}

const NewapiRouteRouteChildren: NewapiRouteRouteChildren = {
  NewapiChannelsRoute: NewapiChannelsRoute,
  NewapiDifferencesRoute: NewapiDifferencesRoute,
  NewapiGroupsRoute: NewapiGroupsRoute,
  NewapiPricesRoute: NewapiPricesRoute,
  NewapiIndexRoute: NewapiIndexRoute,
}

const NewapiRouteRouteWithChildren = NewapiRouteRoute._addFileChildren(
  NewapiRouteRouteChildren,
)

interface UptimeKumaRouteRouteChildren {
  UptimeKumaConfigRoute: typeof UptimeKumaConfigRoute
  UptimeKumaStatusPagesRoute: typeof UptimeKumaStatusPagesRoute
  UptimeKumaTemplatesRoute: typeof UptimeKumaTemplatesRoute
  UptimeKumaIndexRoute: typeof UptimeKumaIndexRoute
}

const UptimeKumaRouteRouteChildren: UptimeKumaRouteRouteChildren = {
  UptimeKumaConfigRoute: UptimeKumaConfigRoute,
  UptimeKumaStatusPagesRoute: UptimeKumaStatusPagesRoute,
  UptimeKumaTemplatesRoute: UptimeKumaTemplatesRoute,
  UptimeKumaIndexRoute: UptimeKumaIndexRoute,
}

const UptimeKumaRouteRouteWithChildren = UptimeKumaRouteRoute._addFileChildren(
  UptimeKumaRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NewapiRouteRoute: NewapiRouteRouteWithChildren,
  UptimeKumaRouteRoute: UptimeKumaRouteRouteWithChildren,
  AccountsRoute: AccountsRoute,
  AlertPolicyRoute: AlertPolicyRoute,
  AlertsRoute: AlertsRoute,
  AutoInspectionRoute: AutoInspectionRoute,
  ConfigRoute: ConfigRoute,
  GroupsRoute: GroupsRoute,
  LogsRoute: LogsRoute,
  ModelCheckRoute: ModelCheckRoute,
  OnboardingRoute: OnboardingRoute,
  PolicyRoute: PolicyRoute,
  PricingRoute: PricingRoute,
  PricingConfigRoute: PricingConfigRoute,
  ProfileRoute: ProfileRoute,
  RevenueAnalysisRoute: RevenueAnalysisRoute,
  SystemInfoRoute: SystemInfoRoute,
  TraceRoute: TraceRoute,
  TrafficRoute: TrafficRoute,
  UpstreamsRoute: UpstreamsRoute,
  VaultRoute: VaultRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
