import type { AccountStatus, PolicySnapshot, Task } from "@/api";

export const account: AccountStatus = {
  id: "41",
  name: "待校验账号",
  groups: ["codex"],
  upstream_id: "upstream-1",
  upstream_host: "api.example.test",
  upstream_type: "newapi",
  schedulable: true,
  priority: 1,
  load_factor: "1",
  concurrency: 10,
  multiplier: "0.1",
  balance: "10",
  paused: false,
  paused_reason: null,
  routing_state: "healthy",
  health_status: "healthy",
  health: "healthy",
  desired_health: "healthy",
  apply_pending: false,
  apply_error: null,
  decision_state: "applied",
  decision_reason: null,
  failure_streak: 0,
  recovery_pass_streak: 0,
  target_priority: 1,
  target_load_factor: "1",
  target_schedulable: true,
  target_concurrency: 10,
  health_score: 100,
  short_score: 100,
  long_score: 100,
  sample_count: 1,
  recent_results: [],
  ttfb_p50_ms: 100,
  ttfb_p95_ms: 200,
  weight: 1,
};

export const policy: PolicySnapshot = {
  available: true,
  source: "console",
  mode: "完全模式",
  global_strategy: "balanced",
  group_strategies: [],
  missing_rate_fallback: null,
  change_threshold: null,
  cooldown_seconds: null,
  auto_apply: null,
  excluded_group_ids: [],
  traffic_enabled: null,
  probe_interval_seconds: 300,
  probe_model: null,
  traffic_lookback_minutes: null,
  max_samples_per_account: null,
  advanced_policy: {},
  configuration_errors: [],
};

export function task(id: string, status: Task["status"] = "succeeded"): Task {
  return {
    id,
    operation: "account-maintenance",
    skill: "accounts",
    status,
    result: {},
    message: "",
    progress: status === "succeeded" ? 100 : 0,
    created_at: "2026-09-07T00:00:00Z",
    updated_at: "2026-09-07T00:00:00Z",
  };
}
